name: Villagers
version: 1.0-SNAPSHOT
main: me.espada.villagers.Villagers
api-version: 1.15
authors: [Espada]
description: A plugin that lets you controle the villagers based on mobs
website: www.isnanemc.net
commands:

  villageredit:
    description: used this command to edit the delay and the period values
    aliases: ve
    permission: villagers.edit

  villagermutate:
    description: used to mutate a villager to a custom villager
    aliases: vm
    permission: villagers.mutate

  villagerspawn:
    description: used to spawn a custom villager
    aliases: vs
    permission: villagers.spawn
